name: flutter_bootstrap_widgets_example
description: Demonstrates how to use the flutter_bootstrap_widgets plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bootstrap_widgets:
    path: ../

  cupertino_icons: ^1.0.0
  flutter_admin_scaffold: ^0.0.2
  flutter_bootstrap: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
