name: flutter_bootstrap_widgets
description: A bundle of Bootstrap 3 style widgets.
version: 0.0.5
homepage: https://github.com/keyber-inc/flutter_bootstrap_widgets

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:

